/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_markup_salon_models_JNI */

#ifndef _Included_com_markup_salon_models_JNI
#define _Included_com_markup_salon_models_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_markup_salon_models_JNI
 * Method:    salonsDataToTxt
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_markup_salon_models_JNI_salonsDataToTxt
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
